# First Test: Importing java classes into Python

## DW(2015.25.11)

In [1]:
import javabridge
import numpy as np

Importing javabridge only works with a 32 bit Python version. 
With 64 Bit python version you will get 'ImportError: DLL load failed: %1 is not a valid Win32 application'.

In [2]:
import gitInformation

In [3]:
# Start the Virtual machine
javabridge.start_vm()

In [4]:
gitInformation.printInformation()

Information about this notebook
Date: 2015-11-27
Python Version: 2.7.10 |Anaconda 2.4.0 (32-bit)| (default, Oct 28 2015, 14:01:20) [MSC v.1500 32 bit (Intel)]
Git directory: C:\Users\Dominik\Documents\GitRep\nounoup\.git
Current git SHA: a068c9c35afbebbea8ef242642710d8627858e74
Remotes: origin, 
Current branch: master
origin remote URL: https://github.com/dowa4213/nounoup.git


## Run Java  Classes

In [5]:
pi = javabridge.run_script('java.lang.Math.PI')

In [6]:
pi

3.141592653589793

In [7]:
log = javabridge.run_script('java.lang.Math.log10(1000)')

In [8]:
log

3.0

In [9]:
sqrt = javabridge.run_script('java.lang.Math.sqrt(100)')

In [10]:
sqrt

10.0

# Handling arrays

In [11]:
env = javabridge.get_env()
# Generating a np.ndarray.
a = np.ones(23)
# Transform it into a Java double array.
s = env.make_double_array(a)
# Transform the Java array to a np.ndarray
c = env.get_double_array_elements(s)

In [12]:
# s is now a Java object.
s

In [13]:
# c is the Java object transformed into a numpy array.
c

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [14]:
c == a

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True], dtype=bool)

It is important to know the type of the array elements, otherwise you will get a array filled with 0.

In [15]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
# Generating a java int array
s = env.make_int_array(a)
# Get the elements as double
b = env.get_double_array_elements(s)

In [16]:
b

array([  6.36598737e-314,   1.06099790e-313,   1.48539705e-313,
         1.90979621e-313,   1.04260903e-315,   0.00000000e+000,
         0.00000000e+000,   0.00000000e+000,   0.00000000e+000])

In [17]:
a == b 

array([False, False, False, False, False, False, False, False, False], dtype=bool)

## Handling Strings

In [18]:
# Generating a Java string  and get the length 
stringLength = javabridge.run_script('sj2 = java.lang.String("Hello"); sj2.length()')

In [19]:
stringLength

5

In [20]:
# Generating a string at split it at the commas.
sj = javabridge.run_script('sj2 = java.lang.String("Hello, my name, is Kenta"); sj2.split(",")')

In [21]:
sj

In [22]:
# Get the length of the array.
env.get_array_length(sj)

3

In [23]:
# Get the  array elements. 
for obj in env.get_object_array_elements(sj):
    print  env.get_string_utf(obj)

Hello
 my name
 is Kenta


## Kill JVM

In [24]:
# Kill the JVM
javabridge.kill_vm()

Once you have killed the JVM, it is not possible to start it again. You have to restart the kernel and start the VM again.

In [25]:
javabridge.start_vm()

Traceback (most recent call last):
  File "c:\users\dominik\desktop\javabridge-1.0.11\javabridge\jutil.py", line 251, in start_thread
    env = vm.create(args)
  File "_javabridge.pyx", line 609, in _javabridge.JB_VM.create (_javabridge.c:6060)
RuntimeError: Failed to create Java VM. Return code = -1
ERROR:javabridge.jutil:Failed to create Java VM


RuntimeError: Failed to start Java VM